# Generated by Django 3.2.9 on 2022-01-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_favoriteadvs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.TextField(choices=[('OPEN', 'Открыто'), ('CLOSED', 'Закрыто'), ('DRAFT', 'Черновик')], default='OPEN', verbose_name='Cтатус'),
        ),
        migrations.DeleteModel(
            name='FavoriteAdvs',
        ),
    ]
